[build]
packages = [
    "pyroll" # place your package in the pyroll namespace
]

[metadata]
allow-direct-references = true

[version]
path = "pyroll/interface_friction.py"

[envs.default]
path = ".venv"
dependencies = [
    "pytest ~= 7.0",
    "matplotlib ~= 3.6",
    "pyroll-report ~= 3.0",
]

[envs.docs]
path = ""
dependencies = [
    "pygments ~= 2.0",
    "pytask",
    "pytask-latex",
    "matplotlib"
]

[envs.docs.scripts]
build = "python -m pytask" # compile LaTeX docs with latexmk

[envs.test]
path = ""

[envs.test.scripts]
all = "pytest"

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]